println "A '\b' Backspace"
println "A '\t' Tab"
println "A '\r' Carriage return"
println "A '\n' Line feed"
println "A '\f' Form feed"
println "A '\\' Backslash"
println "A '\$' Dollar sign"
println "A '\u00A9' (Copyright symbol) - Unicode character U+00A9"
println "A '\54' (Comma) - ASCII code 44 (44 decimal = 54 octal)"
println "A '\'' Single quote"
println "A '\"' Double quote"
