@Grab('org.hsqldb:hsqldb:2.3.2')
@GrabConfig(systemClassLoader=true)
//////////////////////////////////




import groovy.sql.Sql

def url = 'jdbc:hsqldb:mem:GinA'
def user = 'sa'
def password = ''
def driver = 'org.hsqldb.jdbcDriver'
def sql = Sql.newInstance(url, user, password, driver)

sql.execute '''
  CREATE TABLE Athlete (
    athleteId   INTEGER GENERATED BY DEFAULT AS IDENTITY,    --#A
    firstname   VARCHAR(64),
    lastname    VARCHAR(64),
    dateOfBirth DATE
  );
'''

sql.close()
//#A Column value will be automatically generated